In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('diabetes_dataset00.csv')

In [ ]:
df.head()

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
0,Steroid-Induced Diabetes,Positive,Negative,No,Present,40,44,38,High,Healthy,...,76.0,No,No,Positive,3.0,Normal,56.0,Ketones Present,2629.0,No
1,Neonatal Diabetes Mellitus (NDM),Positive,Negative,No,Present,13,1,17,High,Healthy,...,60.0,Yes,No,Negative,1.0,Normal,28.0,Glucose Present,1881.0,Yes
2,Prediabetic,Positive,Positive,Yes,Present,27,36,24,High,Unhealthy,...,80.0,Yes,No,Negative,1.0,Abnormal,55.0,Ketones Present,3622.0,Yes
3,Type 1 Diabetes,Negative,Positive,No,Present,8,7,16,Low,Unhealthy,...,89.0,Yes,No,Positive,2.0,Abnormal,60.0,Ketones Present,3542.0,No
4,Wolfram Syndrome,Negative,Negative,Yes,Present,17,10,17,High,Healthy,...,41.0,No,No,Positive,1.0,Normal,24.0,Protein Present,1770.0,No

In [ ]:
df.head(10)

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
0,Steroid-Induced Diabetes,Positive,Negative,No,Present,40,44,38,High,Healthy,...,76.0,No,No,Positive,3.0,Normal,56.0,Ketones Present,2629.0,No
1,Neonatal Diabetes Mellitus (NDM),Positive,Negative,No,Present,13,1,17,High,Healthy,...,60.0,Yes,No,Negative,1.0,Normal,28.0,Glucose Present,1881.0,Yes
2,Prediabetic,Positive,Positive,Yes,Present,27,36,24,High,Unhealthy,...,80.0,Yes,No,Negative,1.0,Abnormal,55.0,Ketones Present,3622.0,Yes
3,Type 1 Diabetes,Negative,Positive,No,Present,8,7,16,Low,Unhealthy,...,89.0,Yes,No,Positive,2.0,Abnormal,60.0,Ketones Present,3542.0,No
4,Wolfram Syndrome,Negative,Negative,Yes,Present,17,10,17,High,Healthy,...,41.0,No,No,Positive,1.0,Normal,24.0,Protein Present,1770.0,No
5,LADA,Positive,Negative,Yes,Present,17,41,26,Moderate,Healthy,...,85.0,Yes,No,Negative,2.0,Normal,52.0,Ketones Present,3835.0,Yes
6,Type 2 Diabetes,Negative,Negative,No,Absent,29,30,31,Moderate,Healthy,...,64.0,Yes,Yes,Negative,3.0,Abnormal,96.0,Ketones Present,4426.0,No
7,Wolcott-Rallison Syndrome,Positive,Negative,No,Absent,10,3,18,Low,Unhealthy,...,44.0,Yes,No,Negative,1.0,Normal,29.0,Ketones Present,1644.0,Yes
8,Secondary Diabetes,Negative,Positive,No,Absent,47,47,25,High,Healthy,...,71.0,No,Yes,Positive,3.0,Normal,74.0,Ketones Present,3721.0,No
9,Secondary Diabetes,Positive,Negative,Yes,Present,21,72,24,Low,Unhealthy,...,69.0,Yes,Yes,Positive,2.0,Abnormal,42.0,Protein Present,4206.0,No

In [ ]:
df.head(100)

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
0,Steroid-Induced Diabetes,Positive,Negative,No,Present,40,44,38,High,Healthy,...,76.0,No,No,Positive,3.0,Normal,56.0,Ketones Present,2629.0,No
1,Neonatal Diabetes Mellitus (NDM),Positive,Negative,No,Present,13,1,17,High,Healthy,...,60.0,Yes,No,Negative,1.0,Normal,28.0,Glucose Present,1881.0,Yes
2,Prediabetic,Positive,Positive,Yes,Present,27,36,24,High,Unhealthy,...,80.0,Yes,No,Negative,1.0,Abnormal,55.0,Ketones Present,3622.0,Yes
3,Type 1 Diabetes,Negative,Positive,No,Present,8,7,16,Low,Unhealthy,...,89.0,Yes,No,Positive,2.0,Abnormal,60.0,Ketones Present,3542.0,No
4,Wolfram Syndrome,Negative,Negative,Yes,Present,17,10,17,High,Healthy,...,41.0,No,No,Positive,1.0,Normal,24.0,Protein Present,1770.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Neonatal Diabetes Mellitus (NDM),Positive,Positive,No,Absent,9,0,17,High,Unhealthy,...,73.0,Yes,Yes,Positive,1.0,Normal,24.0,Glucose Present,2755.0,No
96,MODY,Negative,Negative,No,Present,23,18,22,Moderate,Unhealthy,...,86.0,Yes,No,Negative,2.0,Abnormal,37.0,Normal,3962.0,Yes
97,Steroid-Induced Diabetes,Positive,Negative,Yes,Absent,42,60,27,Moderate,Unhealthy,...,65.0,No,Yes,Positive,2.0,Normal,67.0,Protein Present,2614.0,No
98,Type 1 Diabetes,Negative,Positive,Yes,Present,10,7,19,High,Unhealthy,...,70.0,No,Yes,Negative,2.0,Abnormal,44.0,Ketones Present,3622.0,Yes
99,Wolcott-Rallison Syndrome,Negative,Negative,Yes,Present,5,5,16,Low,Healthy,...,40.0,No,Yes,Positive,2.0,Normal,17.0,Glucose Present,2167.0,Yes

In [ ]:
df.tail()

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
10269,Type 3c Diabetes (Pancreatogenic Diabetes),Positive,Negative,No,Absent,28,52,34,Low,Unhealthy,...,63.0,Yes,Yes,Positive,3.0,Normal,60.0,Protein Present,2502.0,No
10270,Type 2 Diabetes,Negative,Positive,No,Present,32,55,39,Moderate,Unhealthy,...,62.0,No,Yes,Negative,2.0,Normal,83.0,Glucose Present,3032.0,No
10271,Neonatal Diabetes Mellitus (NDM),Positive,Negative,No,Absent,7,0,16,Moderate,Healthy,...,50.0,No,Yes,Negative,1.0,Normal,27.0,Normal,1884.0,No
10272,Wolcott-Rallison Syndrome,Negative,Negative,Yes,Absent,7,2,23,High,Healthy,...,43.0,No,Yes,Positive,1.0,Abnormal,10.0,Ketones Present,1625.0,Yes
10273,Neonatal Diabetes Mellitus (NDM),Negative,Negative,Yes,Present,8,1,17,L,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.tail(10)

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
10264,Type 2 Diabetes,Negative,Negative,Yes,Present,32,76,37,High,Healthy,...,62.0,No,Yes,Negative,2.0,Normal,93.0,Normal,2525.0,Yes
10265,Steroid-Induced Diabetes,Negative,Negative,No,Absent,19,46,32,Moderate,Unhealthy,...,76.0,No,Yes,Positive,3.0,Normal,62.0,Protein Present,4305.0,Yes
10266,Cystic Fibrosis-Related Diabetes (CFRD),Negative,Positive,No,Present,24,11,20,Moderate,Unhealthy,...,52.0,No,Yes,Positive,2.0,Normal,32.0,Ketones Present,3515.0,No
10267,Gestational Diabetes,Negative,Negative,No,Present,14,21,27,Low,Healthy,...,71.0,Yes,Yes,Positive,2.0,Normal,63.0,Protein Present,4001.0,Yes
10268,Secondary Diabetes,Positive,Negative,Yes,Present,30,78,28,Low,Healthy,...,75.0,Yes,Yes,Positive,3.0,Normal,45.0,Ketones Present,4061.0,Yes
10269,Type 3c Diabetes (Pancreatogenic Diabetes),Positive,Negative,No,Absent,28,52,34,Low,Unhealthy,...,63.0,Yes,Yes,Positive,3.0,Normal,60.0,Protein Present,2502.0,No
10270,Type 2 Diabetes,Negative,Positive,No,Present,32,55,39,Moderate,Unhealthy,...,62.0,No,Yes,Negative,2.0,Normal,83.0,Glucose Present,3032.0,No
10271,Neonatal Diabetes Mellitus (NDM),Positive,Negative,No,Absent,7,0,16,Moderate,Healthy,...,50.0,No,Yes,Negative,1.0,Normal,27.0,Normal,1884.0,No
10272,Wolcott-Rallison Syndrome,Negative,Negative,Yes,Absent,7,2,23,High,Healthy,...,43.0,No,Yes,Positive,1.0,Abnormal,10.0,Ketones Present,1625.0,Yes
10273,Neonatal Diabetes Mellitus (NDM),Negative,Negative,Yes,Present,8,1,17,L,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.tail(100)

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
10174,Wolfram Syndrome,Negative,Negative,Yes,Present,10,18,24,Low,Healthy,...,68.0,No,Yes,Positive,2.0,Abnormal,10.0,Protein Present,1937.0,Yes
10175,MODY,Negative,Positive,Yes,Absent,13,14,20,Low,Unhealthy,...,76.0,Yes,No,Negative,2.0,Normal,51.0,Normal,3617.0,No
10176,Type 3c Diabetes (Pancreatogenic Diabetes),Positive,Positive,No,Absent,36,64,29,High,Healthy,...,70.0,Yes,No,Negative,3.0,Normal,40.0,Glucose Present,3363.0,No
10177,Prediabetic,Negative,Positive,No,Present,23,48,25,High,Unhealthy,...,73.0,Yes,Yes,Negative,1.0,Normal,63.0,Normal,2920.0,Yes
10178,Type 2 Diabetes,Negative,Positive,Yes,Present,26,61,33,Low,Unhealthy,...,66.0,Yes,Yes,Positive,2.0,Normal,58.0,Ketones Present,3446.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10269,Type 3c Diabetes (Pancreatogenic Diabetes),Positive,Negative,No,Absent,28,52,34,Low,Unhealthy,...,63.0,Yes,Yes,Positive,3.0,Normal,60.0,Protein Present,2502.0,No
10270,Type 2 Diabetes,Negative,Positive,No,Present,32,55,39,Moderate,Unhealthy,...,62.0,No,Yes,Negative,2.0,Normal,83.0,Glucose Present,3032.0,No
10271,Neonatal Diabetes Mellitus (NDM),Positive,Negative,No,Absent,7,0,16,Moderate,Healthy,...,50.0,No,Yes,Negative,1.0,Normal,27.0,Normal,1884.0,No
10272,Wolcott-Rallison Syndrome,Negative,Negative,Yes,Absent,7,2,23,High,Healthy,...,43.0,No,Yes,Positive,1.0,Abnormal,10.0,Ketones Present,1625.0,Yes
10273,Neonatal Diabetes Mellitus (NDM),Negative,Negative,Yes,Present,8,1,17,L,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(10274, 34)

In [ ]:
df.columns

Index(['Target', 'Genetic Markers', 'Autoantibodies', 'Family History',
       'Environmental Factors', 'Insulin Levels', 'Age', 'BMI',
       'Physical Activity', 'Dietary Habits', 'Blood Pressure',
       'Cholesterol Levels', 'Waist Circumference', 'Blood Glucose Levels',
       'Ethnicity', 'Socioeconomic Factors', 'Smoking Status',
       'Alcohol Consumption', 'Glucose Tolerance Test', 'History of PCOS',
       'Previous Gestational Diabetes', 'Pregnancy History',
       'Weight Gain During Pregnancy', 'Pancreatic Health',
       'Pulmonary Function', 'Cystic Fibrosis Diagnosis',
       'Steroid Use History', 'Genetic Testing', 'Neurological Assessments',
       'Liver Function Tests', 'Digestive Enzyme Levels', 'Urine Test',
       'Birth Weight', 'Early Onset Symptoms'],
      dtype='object')

In [ ]:
df.dtypes

Target                            object
Genetic Markers                   object
Autoantibodies                    object
Family History                    object
Environmental Factors             object
Insulin Levels                     int64
Age                                int64
BMI                                int64
Physical Activity                 object
Dietary Habits                    object
Blood Pressure                   float64
Cholesterol Levels               float64
Waist Circumference              float64
Blood Glucose Levels             float64
Ethnicity                         object
Socioeconomic Factors             object
Smoking Status                    object
Alcohol Consumption               object
Glucose Tolerance Test            object
History of PCOS                   object
Previous Gestational Diabetes     object
Pregnancy History                 object
Weight Gain During Pregnancy     float64
Pancreatic Health                float64
Pulmonary Function               float64
Cystic Fibrosis Diagnosis         object
Steroid Use History               object
Genetic Testing                   object
Neurological Assessments         float64
Liver Function Tests              object
Digestive Enzyme Levels          float64
Urine Test                        object
Birth Weight                     float64
Early Onset Symptoms              object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10274 entries, 0 to 10273
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Target                         10274 non-null  object
 1   Genetic Markers                10274 non-null  object
 2   Autoantibodies                 10274 non-null  object
 3   Family History                 10274 non-null  object
 4   Environmental Factors          10274 non-null  object
 5   Insulin Levels                 10274 non-null  int64
 6   Age                            10274 non-null  int64
 7   BMI                            10274 non-null  int64
 8   Physical Activity              10274 non-null  object
 9   Dietary Habits                 10273 non-null  object
 10  Blood Pressure                 10273 non-null  float64
 11  Cholesterol Levels             10273 non-null  float64
 12  Waist Circumference            10273 non-null  float64
 13  Blood Glucose Levels           10273 non-null  float64
 14  Ethnicity                      10273 non-null  object
 15  Socioeconomic Factors          10273 non-null  object
 16  Smoking Status                 10273 non-null  object
 17  Alcohol Consumption            10273 non-null  object
 18  Glucose Tolerance Test         10273 non-null  object
 19  History of PCOS                10273 non-null  object
 20  Previous Gestational Diabetes  10273 non-null  object
 21  Pregnancy History              10273 non-null  object
 22  Weight Gain During Pregnancy   10273 non-null  float64
 23  Pancreatic Health              10273 non-null  float64
 24  Pulmonary Function             10273 non-null  float64
 25  Cystic Fibrosis Diagnosis      10273 non-null  object
 26  Steroid Use History            10273 non-null  object
 27  Genetic Testing                10273 non-null  object
 28  Neurological Assessments       10273 non-null  float64
 29  Liver Function Tests           10273 non-null  object
 30  Digestive Enzyme Levels        10273 non-null  float64
 31  Urine Test                     10273 non-null  object
 32  Birth Weight                   10273 non-null  float64
 33  Early Onset Symptoms           10273 non-null  object
dtypes: float64(10), int64(3), object(21)
memory usage: 2.7+ MB

In [ ]:
df.describe()

,Insulin Levels,Age,BMI,Blood Pressure,Cholesterol Levels,Waist Circumference,Blood Glucose Levels,Weight Gain During Pregnancy,Pancreatic Health,Pulmonary Function,Neurological Assessments,Digestive Enzyme Levels,Birth Weight
count,10274.000000,10274.000000,10274.000000,10273.000000,10273.000000,10273.000000,10273.000000,10273.000000,10273.000000,10273.000000,10273.000000,10273.000000,10273.000000
mean,21.708390,32.124684,24.840179,111.590772,195.191083,35.082254,160.716928,15.513482,47.404361,70.320646,1.800448,46.753042,3103.749051
std,10.880833,20.906222,6.040790,19.859391,44.555017,6.825480,48.128676,9.562420,19.802501,11.896211,0.682796,19.421337,711.748109
min,5.000000,0.000000,12.000000,60.000000,100.000000,20.000000,80.000000,0.000000,10.000000,30.000000,1.000000,10.000000,1500.000000
25%,13.000000,14.000000,20.000000,100.000000,163.000000,30.000000,121.000000,7.000000,32.000000,63.000000,1.000000,32.000000,2640.000000
50%,19.000000,31.000000,25.000000,113.000000,191.000000,34.000000,151.000000,16.000000,46.000000,72.000000,2.000000,48.000000,3110.000000
75%,28.000000,49.000000,29.000000,125.000000,225.000000,39.000000,194.000000,22.000000,63.000000,79.000000,2.000000,62.000000,3660.000000
max,49.000000,79.000000,39.000000,149.000000,299.000000,54.000000,299.000000,39.000000,99.000000,89.000000,3.000000,99.000000,4499.000000

**CHECK DATA QUALITY**

In [ ]:
# Check for missing values
df.isnull().sum()

Target                           0
Genetic Markers                  0
Autoantibodies                   0
Family History                   0
Environmental Factors            0
Insulin Levels                   0
Age                              0
BMI                              0
Physical Activity                0
Dietary Habits                   1
Blood Pressure                   1
Cholesterol Levels               1
Waist Circumference              1
Blood Glucose Levels             1
Ethnicity                        1
Socioeconomic Factors            1
Smoking Status                   1
Alcohol Consumption              1
Glucose Tolerance Test           1
History of PCOS                  1
Previous Gestational Diabetes    1
Pregnancy History                1
Weight Gain During Pregnancy     1
Pancreatic Health                1
Pulmonary Function               1
Cystic Fibrosis Diagnosis        1
Steroid Use History              1
Genetic Testing                  1
Neurological Assessments         1
Liver Function Tests             1
Digestive Enzyme Levels          1
Urine Test                       1
Birth Weight                     1
Early Onset Symptoms             1
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.nunique()

Target                             13
Genetic Markers                     2
Autoantibodies                      2
Family History                      2
Environmental Factors               2
Insulin Levels                     45
Age                                80
BMI                                28
Physical Activity                   4
Dietary Habits                      2
Blood Pressure                     90
Cholesterol Levels                200
Waist Circumference                35
Blood Glucose Levels              220
Ethnicity                           2
Socioeconomic Factors               3
Smoking Status                      2
Alcohol Consumption                 3
Glucose Tolerance Test              2
History of PCOS                     2
Previous Gestational Diabetes       2
Pregnancy History                   2
Weight Gain During Pregnancy       40
Pancreatic Health                  90
Pulmonary Function                 60
Cystic Fibrosis Diagnosis           2
Steroid Use History                 2
Genetic Testing                     2
Neurological Assessments            3
Liver Function Tests                2
Digestive Enzyme Levels            90
Urine Test                          4
Birth Weight                     2751
Early Onset Symptoms                2
dtype: int64

In [ ]:
df['Age'].unique()

array([44,  1, 36,  7, 10, 41, 30,  3, 47, 72, 67, 29, 59,  0, 45, 53, 60,
       16, 35, 14, 64,  9, 65, 34, 51, 11, 56, 37, 22, 70, 33, 50, 62, 40,
       28, 12, 38, 19, 39, 46, 43, 77, 73, 32,  5, 49, 26, 52, 21, 54, 18,
       42, 31, 23, 58, 13,  8, 48, 55, 17, 24, 25, 79,  6,  2,  4, 69, 27,
       15, 61, 20, 66, 68, 78, 57, 71, 63, 75, 74, 76])

In [ ]:
df['Insulin Levels'].unique()

array([40, 13, 27,  8, 17, 29, 10, 47, 21, 16, 22,  9, 38, 14, 12, 30, 19,
       42, 34, 11, 24, 44, 20, 15, 18,  6, 28, 48,  5, 46, 26, 45, 33, 23,
       41, 39,  7, 31, 35, 25, 32, 36, 43, 49, 37])

In [ ]:
df['BMI'].unique()

array([38, 17, 24, 16, 26, 31, 18, 25, 29, 23, 28, 19, 22, 37, 32, 33, 39,
       34, 15, 21, 27, 35, 14, 20, 12, 13, 30, 36])

In [ ]:
df['Birth Weight'].unique()

array([2629., 1881., 3622., ..., 4001., 1625.,   nan])

In [ ]:
df['Blood Glucose Levels'].unique()

array([168., 178., 105., 121., 289., 142., 186., 206., 160., 192., 114.,
       113., 175., 136., 200., 132., 190., 126.,  93., 167., 234., 161.,
       287., 170., 198., 146., 156., 137., 131., 129., 255., 108., 181.,
       106., 248., 166., 172., 103., 133., 115., 245., 127., 111., 150.,
       112., 223., 219., 120., 188., 239., 123., 221., 240., 185., 154.,
        97., 233., 201., 148., 163., 138., 153., 157., 152., 145., 212.,
       164., 122., 191., 104., 195., 130.,  96., 244., 100., 102., 159.,
       118., 238., 197., 290., 236., 128., 216., 242., 209., 246.,  84.,
       265., 124., 109.,  92., 125., 158.,  94., 237., 232., 107., 203.,
       250., 135., 140., 173., 184., 227., 174., 171., 183., 182., 211.,
       169., 189., 207.,  83., 155.,  95., 116., 101.,  99., 251.,  90.,
       187., 144., 176., 241., 213., 165., 249., 143., 205., 243., 162.,
       199., 273., 274.,  98., 266., 139., 149., 231., 222., 151., 220.,
       194., 134., 117., 228., 119., 264., 226.,  80., 110., 196., 262.,
       269., 256., 224., 230., 179., 147., 193., 218., 272., 217., 295.,
       177., 267., 247., 180., 204., 225., 285., 229., 296., 215., 210.,
       298., 299., 280., 281., 141., 291.,  85., 254., 263., 279., 271.,
       292., 214., 283., 235.,  87., 284., 252., 275., 253.,  91., 288.,
       282., 202.,  81.,  89., 297., 257., 276., 277., 208., 260.,  86.,
       258.,  88.,  82., 268., 261., 278., 294., 286., 270., 293., 259.,
        nan])

In [ ]:
# Check how many zero in Blood Glucose Levels
(df['Blood Glucose Levels']==0).sum()

np.int64(0)

In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('diabetes_dataset00.csv')

In [12]:
# Check how many zero in whole dataset
df.isin([0]).sum()

Target                              0
Genetic Markers                     0
Autoantibodies                      0
Family History                      0
Environmental Factors               0
Insulin Levels                      0
Age                              2655
BMI                                 0
Physical Activity                   0
Dietary Habits                      0
Blood Pressure                      0
Cholesterol Levels                  0
Waist Circumference                 0
Blood Glucose Levels                0
Ethnicity                           0
Socioeconomic Factors               0
Smoking Status                      0
Alcohol Consumption                 0
Glucose Tolerance Test              0
History of PCOS                     0
Previous Gestational Diabetes       0
Pregnancy History                   0
Weight Gain During Pregnancy     2731
Pancreatic Health                   0
Pulmonary Function                  0
Cystic Fibrosis Diagnosis           0
Steroid Use History                 0
Genetic Testing                     0
Neurological Assessments            0
Liver Function Tests                0
Digestive Enzyme Levels             0
Urine Test                          0
Birth Weight                        0
Early Onset Symptoms                0
dtype: int64

In [13]:
# selecting single column
df['BMI']

0        38
1        17
2        24
3        16
4        17
         ..
69995    35
69996    31
69997    15
69998    24
69999    28
Name: BMI, Length: 70000, dtype: int64

In [14]:
(df[['Birth Weight','Blood Pressure','Insulin Levels','Blood Glucose Levels','BMI']]==0).sum()

Birth Weight            0
Blood Pressure          0
Insulin Levels          0
Blood Glucose Levels    0
BMI                     0
dtype: int64

In [15]:
# Selecting multiple columns
df[['Blood Glucose Levels','BMI','Age']]

       Blood Glucose Levels  BMI  Age
0                       168   38   44
1                       178   17    1
2                       105   24   36
3                       121   16    7
4                       289   17   10
...                     ...  ...  ...
69995                   227   35   38
69996                   149   31   51
69997                   143   15   11
69998                   126   24   30
69999                   117   28   41

[70000 rows x 3 columns]

In [16]:
# Filter row with single condition
df[df['Age']>50]

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
9,Secondary Diabetes,Positive,Negative,Yes,Present,21,72,24,Low,Unhealthy,...,69,Yes,Yes,Positive,2,Abnormal,42,Protein Present,4206,No
10,Secondary Diabetes,Negative,Positive,No,Present,16,67,29,Low,Healthy,...,75,No,No,Negative,3,Normal,59,Glucose Present,3965,No
12,Prediabetic,Positive,Negative,No,Absent,22,59,28,Low,Healthy,...,73,Yes,Yes,Positive,1,Abnormal,76,Normal,3588,No
15,Steroid-Induced Diabetes,Positive,Negative,Yes,Present,38,53,37,Low,Unhealthy,...,60,No,Yes,Negative,2,Normal,53,Normal,4239,No
18,Type 3c Diabetes (Pancreatogenic Diabetes),Positive,Negative,No,Present,30,60,32,Moderate,Healthy,...,62,Yes,Yes,Negative,3,Abnormal,41,Normal,4335,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69978,Type 3c Diabetes (Pancreatogenic Diabetes),Positive,Positive,No,Present,23,55,33,Low,Healthy,...,71,No,No,Positive,3,Normal,40,Protein Present,3541,Yes
69986,Secondary Diabetes,Negative,Positive,No,Present,48,55,27,Moderate,Unhealthy,...,63,No,Yes,Negative,2,Normal,49,Normal,2703,No
69988,Secondary Diabetes,Negative,Negative,Yes,Present,28,60,34,Moderate,Healthy,...,68,Yes,Yes,Positive,2,Abnormal,40,Normal,2507,Yes
69993,Steroid-Induced Diabetes,Positive,Positive,Yes,Absent,20,64,32,Low,Healthy,...,68,No,Yes,Positive,3,Normal,33,Protein Present,4332,No
69996,LADA,Positive,Positive,No,Absent,21,51,31,Low,Unhealthy,...,82,Yes,Yes,Negative,1,Abnormal,58,Ketones Present,3002,No

In [17]:
df[df['BMI']>50]

Empty DataFrame
Columns: [Target, Genetic Markers, Autoantibodies, Family History, Environmental Factors, Insulin Levels, Age, BMI, Physical Activity, Dietary Habits, Blood Pressure, Cholesterol Levels, Waist Circumference, Blood Glucose Levels, Ethnicity, Socioeconomic Factors, Smoking Status, Alcohol Consumption, Glucose Tolerance Test, History of PCOS, Previous Gestational Diabetes, Pregnancy History, Weight Gain During Pregnancy, Pancreatic Health, Pulmonary Function, Cystic Fibrosis Diagnosis, Steroid Use History, Genetic Testing, Neurological Assessments, Liver Function Tests, Digestive Enzyme Levels, Urine Test, Birth Weight, Early Onset Symptoms]
Index: []

[0 rows x 34 columns]

In [18]:
# Filter rows with multiple conditions
df[(df['Age']>50) & (df['BMI']>50)]

Empty DataFrame
Columns: [Target, Genetic Markers, Autoantibodies, Family History, Environmental Factors, Insulin Levels, Age, BMI, Physical Activity, Dietary Habits, Blood Pressure, Cholesterol Levels, Waist Circumference, Blood Glucose Levels, Ethnicity, Socioeconomic Factors, Smoking Status, Alcohol Consumption, Glucose Tolerance Test, History of PCOS, Previous Gestational Diabetes, Pregnancy History, Weight Gain During Pregnancy, Pancreatic Health, Pulmonary Function, Cystic Fibrosis Diagnosis, Steroid Use History, Genetic Testing, Neurological Assessments, Liver Function Tests, Digestive Enzyme Levels, Urine Test, Birth Weight, Early Onset Symptoms]
Index: []

[0 rows x 34 columns]

In [19]:
df[(df['Age']>50) & (df['Blood Glucose Levels']>50)]

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
9,Secondary Diabetes,Positive,Negative,Yes,Present,21,72,24,Low,Unhealthy,...,69,Yes,Yes,Positive,2,Abnormal,42,Protein Present,4206,No
10,Secondary Diabetes,Negative,Positive,No,Present,16,67,29,Low,Healthy,...,75,No,No,Negative,3,Normal,59,Glucose Present,3965,No
12,Prediabetic,Positive,Negative,No,Absent,22,59,28,Low,Healthy,...,73,Yes,Yes,Positive,1,Abnormal,76,Normal,3588,No
15,Steroid-Induced Diabetes,Positive,Negative,Yes,Present,38,53,37,Low,Unhealthy,...,60,No,Yes,Negative,2,Normal,53,Normal,4239,No
18,Type 3c Diabetes (Pancreatogenic Diabetes),Positive,Negative,No,Present,30,60,32,Moderate,Healthy,...,62,Yes,Yes,Negative,3,Abnormal,41,Normal,4335,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69978,Type 3c Diabetes (Pancreatogenic Diabetes),Positive,Positive,No,Present,23,55,33,Low,Healthy,...,71,No,No,Positive,3,Normal,40,Protein Present,3541,Yes
69986,Secondary Diabetes,Negative,Positive,No,Present,48,55,27,Moderate,Unhealthy,...,63,No,Yes,Negative,2,Normal,49,Normal,2703,No
69988,Secondary Diabetes,Negative,Negative,Yes,Present,28,60,34,Moderate,Healthy,...,68,Yes,Yes,Positive,2,Abnormal,40,Normal,2507,Yes
69993,Steroid-Induced Diabetes,Positive,Positive,Yes,Absent,20,64,32,Low,Healthy,...,68,No,Yes,Positive,3,Normal,33,Protein Present,4332,No
69996,LADA,Positive,Positive,No,Absent,21,51,31,Low,Unhealthy,...,82,Yes,Yes,Negative,1,Abnormal,58,Ketones Present,3002,No

In [20]:
# Access rows by index(iloc)
df.iloc[10:15]

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
10,Secondary Diabetes,Negative,Positive,No,Present,16,67,29,Low,Healthy,...,75,No,No,Negative,3,Normal,59,Glucose Present,3965,No
11,Type 1 Diabetes,Positive,Negative,No,Absent,8,29,23,Low,Unhealthy,...,75,No,No,Negative,1,Abnormal,60,Ketones Present,2947,No
12,Prediabetic,Positive,Negative,No,Absent,22,59,28,Low,Healthy,...,73,Yes,Yes,Positive,1,Abnormal,76,Normal,3588,No
13,Neonatal Diabetes Mellitus (NDM),Positive,Positive,No,Present,9,0,19,Low,Unhealthy,...,56,No,Yes,Negative,1,Normal,29,Glucose Present,2202,No
14,LADA,Negative,Negative,No,Absent,21,45,22,Moderate,Healthy,...,76,No,No,Positive,2,Normal,43,Protein Present,2984,No

In [21]:
df.iloc[30:40]

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
30,Steroid-Induced Diabetes,Negative,Negative,Yes,Absent,44,51,34,High,Healthy,...,66,No,No,Positive,3,Normal,59,Protein Present,4068,Yes
31,Neonatal Diabetes Mellitus (NDM),Positive,Negative,No,Present,11,0,18,Moderate,Unhealthy,...,73,No,No,Positive,2,Normal,25,Glucose Present,2889,No
32,Type 2 Diabetes,Positive,Positive,No,Present,20,56,31,Moderate,Healthy,...,71,No,No,Negative,3,Abnormal,49,Glucose Present,3079,Yes
33,Gestational Diabetes,Negative,Positive,Yes,Absent,18,37,33,High,Healthy,...,74,No,Yes,Negative,1,Abnormal,59,Normal,3798,No
34,Wolfram Syndrome,Positive,Negative,No,Present,11,10,15,Low,Unhealthy,...,64,Yes,No,Negative,2,Normal,27,Normal,1596,No
35,LADA,Positive,Negative,No,Absent,10,45,25,High,Healthy,...,87,Yes,No,Negative,1,Normal,35,Protein Present,3682,Yes
36,Type 1 Diabetes,Positive,Negative,Yes,Present,6,22,22,High,Unhealthy,...,84,Yes,No,Positive,1,Abnormal,68,Ketones Present,2575,No
37,Gestational Diabetes,Negative,Positive,Yes,Absent,28,34,26,Low,Healthy,...,80,Yes,No,Positive,2,Abnormal,56,Ketones Present,2855,Yes
38,Type 2 Diabetes,Positive,Positive,Yes,Absent,44,70,34,Low,Unhealthy,...,73,No,No,Positive,3,Normal,83,Protein Present,2633,No
39,Gestational Diabetes,Negative,Negative,Yes,Present,15,33,28,High,Healthy,...,82,Yes,No,Positive,1,Normal,63,Normal,2566,Yes

**SORTING AND GROUPING**

In [22]:
df.sort_values(by='Age',ascending=True).head()

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
17212,Neonatal Diabetes Mellitus (NDM),Negative,Negative,Yes,Absent,6,0,14,High,Healthy,...,70,Yes,Yes,Negative,2,Abnormal,22,Normal,1793,Yes
20781,Neonatal Diabetes Mellitus (NDM),Negative,Negative,No,Absent,9,0,13,Low,Unhealthy,...,51,Yes,No,Positive,2,Normal,10,Ketones Present,2574,Yes
36740,Neonatal Diabetes Mellitus (NDM),Positive,Positive,Yes,Present,14,0,13,Moderate,Unhealthy,...,61,No,No,Negative,1,Normal,13,Protein Present,2661,No
52769,Neonatal Diabetes Mellitus (NDM),Positive,Positive,No,Present,5,0,15,Low,Unhealthy,...,65,No,No,Positive,2,Normal,10,Protein Present,2086,Yes
36761,Neonatal Diabetes Mellitus (NDM),Negative,Negative,Yes,Absent,5,0,19,High,Healthy,...,51,Yes,No,Negative,2,Abnormal,11,Ketones Present,1657,No

In [23]:
df.sort_values(by='Age',ascending=True).tail()

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
32573,Secondary Diabetes,Positive,Positive,Yes,Present,42,79,28,High,Healthy,...,67,No,Yes,Negative,2,Abnormal,59,Normal,3482,Yes
43799,Type 2 Diabetes,Negative,Positive,No,Present,47,79,38,Moderate,Unhealthy,...,72,No,Yes,Positive,2,Normal,50,Normal,2606,No
15261,Secondary Diabetes,Negative,Negative,No,Absent,12,79,30,High,Unhealthy,...,64,No,No,Positive,2,Abnormal,53,Glucose Present,3692,No
15181,Secondary Diabetes,Positive,Negative,No,Present,31,79,31,Low,Healthy,...,77,No,No,Positive,3,Normal,67,Glucose Present,3626,Yes
15194,Secondary Diabetes,Positive,Negative,Yes,Absent,37,79,33,Moderate,Unhealthy,...,73,Yes,Yes,Positive,3,Abnormal,70,Normal,2721,Yes

In [25]:
df['BMI'].value_counts()

BMI
24    4864
27    4184
26    4146
25    4080
28    4016
22    3804
23    3796
20    3426
21    3357
18    3100
19    3075
29    3034
32    2658
30    2650
34    2626
33    2626
31    2592
17    2313
16    2277
15    2256
12     693
14     692
13     667
38     638
36     612
35     611
37     609
39     598
Name: count, dtype: int64

**GROUP BY AND AGGREGATE**

In [33]:
df.groupby('BMI').mean(numeric_only=True)

,Insulin Levels,Age,Blood Pressure,Cholesterol Levels,Waist Circumference,Blood Glucose Levels,Weight Gain During Pregnancy,Pancreatic Health,Pulmonary Function,Neurological Assessments,Digestive Enzyme Levels,Birth Weight
BMI,,,,,,,,,,,,
12,9.427128,0.503608,69.873016,149.414141,24.502165,160.647908,4.506494,24.568543,64.367965,1.479076,19.538240,2236.382395
13,9.556222,0.464768,69.250375,148.377811,24.542729,158.625187,4.485757,24.899550,64.248876,1.521739,19.532234,2270.367316
14,9.504335,0.554913,69.226879,149.144509,24.365607,158.719653,4.640173,24.213873,63.871387,1.504335,19.777457,2258.549133
15,11.847961,8.344415,88.876330,150.331117,28.152482,181.301862,5.540780,31.406472,62.119238,1.511082,26.332004,2429.147163
16,12.067633,8.967062,89.818182,151.499780,28.260430,181.281072,5.880545,31.847167,62.427756,1.489679,27.352657,2443.931489
17,11.754431,8.608301,88.974492,151.351059,28.228275,181.064419,5.676610,31.610463,62.329010,1.488975,26.324687,2419.239516
18,14.324839,12.207742,94.296452,157.807097,29.461613,166.430000,7.919677,37.371613,65.886452,1.496774,33.061613,2647.749355
19,14.440000,12.017886,93.979837,158.399350,29.338211,166.029268,7.879024,36.808780,65.633171,1.488455,33.546016,2641.169431
20,18.276708,22.690601,105.790718,175.177758,32.911851,159.978984,11.403970,44.280794,69.225628,1.569469,41.070636,2936.661705
21,18.193327,22.552875,106.017277,175.675603,32.913018,159.902592,11.377718,45.132857,69.051534,1.574620,41.225201,2945.737265
22,19.667455,26.475289,108.297056,182.615668,33.991588,166.220294,12.951630,46.231861,68.744479,1.686909,42.671924,2993.274974
23,19.569810,26.872761,108.670706,183.085616,33.825079,163.977608,13.147260,46.507376,69.098525,1.690727,43.022392,2998.723656
24,19.538651,30.588199,110.835938,187.707648,34.241571,152.618421,14.405016,47.810033,71.263363,1.629934,46.861431,3046.218133
25,24.859314,42.251471,120.083088,212.903186,37.446078,144.415441,19.645588,54.807598,74.843137,1.871078,55.079167,3367.294853
26,24.608297,42.545586,120.603956,213.702605,37.500241,144.883020,19.954414,54.607815,74.911481,1.883743,55.739026,3379.398456
27,25.090822,43.087715,120.931166,212.946941,37.596797,146.004780,19.626673,53.994503,74.735421,1.870459,55.542782,3375.319551
28,24.959661,42.883466,120.760956,213.342629,37.513446,145.601594,19.771414,54.138944,74.991783,1.890687,55.845369,3373.066484
29,26.774885,42.557350,121.328279,214.750494,38.374753,158.989453,20.296968,54.166117,73.191167,2.022083,54.434410,3404.750824
30,28.230943,46.639623,124.121509,222.313208,39.323019,164.680755,21.211698,54.766038,72.382642,2.101887,55.504906,3434.740377
31,28.302469,46.602238,124.107253,222.374228,39.479938,165.667824,21.232253,53.993827,72.452546,2.099923,55.033951,3437.557485
32,28.164409,47.002634,124.380737,221.751693,39.490594,165.151994,21.123777,55.196764,71.929646,2.111738,55.355154,3440.338224
33,28.164890,45.538462,123.357959,219.672125,39.138995,164.258187,21.315689,54.167174,72.214395,2.081874,54.758187,3431.468774
34,28.067784,46.293222,124.073115,220.633663,39.281417,164.651561,21.249810,54.599391,72.250571,2.111957,55.194973,3452.584158
35,30.319149,53.127660,129.387889,249.481178,42.738134,175.302782,24.906710,56.579378,69.292962,2.502455,61.577741,3464.415712
36,30.228758,52.790850,129.655229,251.284314,42.248366,172.517974,24.872549,55.738562,69.545752,2.509804,60.514706,3504.467320
37,30.701149,51.715928,129.513957,249.668309,42.863711,176.123153,24.495895,55.101806,69.435140,2.486043,59.031199,3493.579639
38,31.804075,52.346395,129.373041,248.672414,43.051724,173.938871,25.255486,56.421630,69.203762,2.520376,60.377743,3434.811912
39,30.744147,51.794314,129.421405,250.628763,42.785953,176.889632,24.234114,53.620401,69.520067,2.505017,60.060201,3508.197324

In [34]:
df['BMI'].mean()

np.float64(24.782942857142856)

In [35]:
df['Age'].mean()

np.float64(32.0207)

In [39]:
age_mode = df['Age'].mode()[0]
age_mode

np.int64(1)

In [40]:
mode_count = (df['Age']== age_mode).sum()

In [41]:
mode_count

np.int64(3165)

In [43]:
df['Age'].std()

21.043173246867614

In [44]:
df['BMI'].std()

6.014235736748566

In [46]:
df.corr(numeric_only=True)

,Insulin Levels,Age,BMI,Blood Pressure,Cholesterol Levels,Waist Circumference,Blood Glucose Levels,Weight Gain During Pregnancy,Pancreatic Health,Pulmonary Function,Neurological Assessments,Digestive Enzyme Levels,Birth Weight
Insulin Levels,1.000000,0.608128,0.534044,0.581814,0.551892,0.580608,0.102301,0.510186,0.295518,0.123034,0.411620,0.398418,0.396347
Age,0.608128,1.000000,0.662997,0.763398,0.730426,0.733633,0.027659,0.698480,0.444710,0.261972,0.482672,0.581695,0.523554
BMI,0.534044,0.662997,1.000000,0.654009,0.603086,0.620750,-0.047480,0.588552,0.386623,0.233309,0.372847,0.523032,0.476306
Blood Pressure,0.581814,0.763398,0.654009,1.000000,0.674503,0.712538,0.011924,0.666891,0.438638,0.259290,0.440803,0.577388,0.539148
Cholesterol Levels,0.551892,0.730426,0.603086,0.674503,1.000000,0.672560,-0.037656,0.692473,0.413477,0.277911,0.477688,0.559936,0.523226
Waist Circumference,0.580608,0.733633,0.620750,0.712538,0.672560,1.000000,0.092852,0.622174,0.371773,0.180723,0.475211,0.487710,0.476957
Blood Glucose Levels,0.102301,0.027659,-0.047480,0.011924,-0.037656,0.092852,1.000000,-0.142277,-0.311547,-0.597521,0.262380,-0.336883,-0.295436
Weight Gain During Pregnancy,0.510186,0.698480,0.588552,0.666891,0.692473,0.622174,-0.142277,1.000000,0.464724,0.350113,0.423865,0.639297,0.570781
Pancreatic Health,0.295518,0.444710,0.386623,0.438638,0.413477,0.371773,-0.311547,0.464724,1.000000,0.421684,0.155210,0.501860,0.451777
Pulmonary Function,0.123034,0.261972,0.233309,0.259290,0.277911,0.180723,-0.597521,0.350113,0.421684,1.000000,-0.032946,0.456181,0.441958
Neurological Assessments,0.411620,0.482672,0.372847,0.440803,0.477688,0.475211,0.262380,0.423865,0.155210,-0.032946,1.000000,0.246517,0.253987
Digestive Enzyme Levels,0.398418,0.581695,0.523032,0.577388,0.559936,0.487710,-0.336883,0.639297,0.501860,0.456181,0.246517,1.000000,0.555680
Birth Weight,0.396347,0.523554,0.476306,0.539148,0.523226,0.476957,-0.295436,0.570781,0.451777,0.441958,0.253987,0.555680,1.000000